name: Update Articles

on:
  schedule:
    - cron:  '30 23 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run script to get current temprature
        run: |
          ./queryWeather.sh

      - name: Commit to the repo
        run: |
          git config --global user.name 'itstusharp'
          git add .
          git commit -am "Update current temprature"
          git push